#ifndef CONNECTIONERROR_H
#define CONNECTIONERROR_H

enum class ZJU_ERROR
{
    NONE,
    INVALID_DETAIL,
    BRUTE_FORCE,
    OTHER_LOGIN_FAILED,
    ACCESS_DENIED,
    LISTEN_FAILED,
    CLIENT_FAILED,
    CAPTCHA_FAILED,
    PROGRAM_NOT_FOUND,
    INTERACTIVE_ERROR,
    AUTH_NOT_AVAILABLE,
    AUTH_EXPIRED,
    OTHER,
};

#endif // CONNECTIONERROR_H
